### PR TITLE
Avoid caching issues on complex class loader scenarios

### LINKED ISSUE #31: ServiceLoader caching is problematic for calls from different classloaders
On a "complex" class loader scheme such as for Application Servers (WildFly, in my case), caching the outcome of the `ServiceLoader.load()` operation leads to wrong results.

Scenario:

Class loader "CLA" contains `TracerResolver`
Class loader "CLB" contains "Application 1" and has "CLA" as parent
Class loader "CLC" contains "Application 2" and has "CLA" as parent
"Application 1" has a custom `TracerResolver` (such as `MockTracerResolver`)
"Application 2" has a custom `TracerResolver` (such as `JaegerTracerResolver`)

The "Application 1" is able to correctly load tracers from the tracer resolver, as it's the first to be loaded. When the "Application 2" calls `resolveTracer()`, it yields (correctly) `null`, as the ServiceLoader instance created by the `TracerResolver` has the class loader `CLB` implicitly set by the first call to the `load(Class<S>)` operation. A `reload()` operation has no effect, as it uses the same classloader.

A solution is to *not* cache or lazily initialize the service loader instances. Rather, load services every time the `resolveTracer()` method is called.

### PR DESCRIPTION
**Pull request by jpkrohling**
Closes #31 .
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

File: opentracing-tracerresolver/src/main/java/io/opentracing/contrib/tracerresolver/TracerResolver.java [hunk 1]
```diff
@@ -95,10 +92,7 @@ public static Tracer resolveTracer() {
      * Reloads the lazily found {@linkplain TracerResolver resolvers} and the fallback resolver.
      */
     public static void reload() {
```
Comment (sjoerdtalsma) [inline opentracing-tracerresolver/src/main/java/io/opentracing/contrib/tracerresolver/TracerResolver.java]: Since `reload()` effectively became a no-op, should we deprecate it's use with an explanation why?

**Review by sjoerdtalsma — APPROVED** [review]
Overall I approve, just one comment about maybe deprecating the `reload` method if it's now a no-op?

**Comment by jpkrohling** [comment]
PR updated to include a deprecation notice.

**Comment by sjoerdtalsma** [comment]
All checks pass, merging to master.

**Comment by sjoerdtalsma** [comment]
@jpkrohling Would you prefer me to trigger a release now, or do you wish to split off the factory code all in one go? 

I'm leaning towards a release now.

**Comment by jpkrohling** [comment]
I just sent a PR for the factory. If you think it's also good to go, the release could be done after that one.
